development:
  adapter: postgresql
  database: stackoverflow_development
  host: localhost
  encoding: UTF8
  min_messages: WARNING

test: &test
  adapter: postgresql
  database: stackoverflow_test
  host: localhost
  encoding: UTF8
  min_messages: WARNING

production:
  adapter: postgresql
  database: stackoverflow_production
  pool: 25
  timeout: 5000
