development:
  adapter: postgresql
  database: fantasy_sos_development
  host: localhost
  encoding: UTF8
  min_messages: WARNING

test: &test
  adapter: postgresql
  database: fantasy_sos_test
  host: localhost
  encoding: UTF8
  min_messages: WARNING

production:
  adapter: postgresql
  database: fantasy_sos_production
  pool: 25
  timeout: 5000
